version: "3"

services:
    postgres:
        image: postgres:14
        container_name: reserch_postgres
        ports:
            - 5432:5432
        volumes:
            # - postgres-store:/var/lib/postgresql/data
            - ./postgresql/conf:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_PASSWORD=passward
    mongo:
        mongo:
        container_name: mongo
        image: mongo:4
        command: --replSet rs0
        ports:
            - "27017:27017"
            - "28017:28017"
        volumes:
            - ../mongodb/mongo:/data/dbc
    voicevox:
        container_name: voicevox
        image: "voicevox/voicevox_engine:cpu-ubuntu20.04-latest"
        # ports:
        # - "50021:50021"
    broker-service:
        container_name: broker-service
        build:
            context: ./../broker-service
            dockerfile: ./../broker-service/broker-service.Dockerfile
        ports:
            - "8080:8080"
    speaker-service:
        container_name: speaker-service
        build:
            context: ./../speaker-service
            dockerfile: ./../speaker-service/speaker-service.Dockerfile
        # ports:
        #   - "8082:8080"
    medicine-api:
        container_name: test_medmanage
        build:
            context: ../medicine-api
            dockerfile: ../medicine-api/Dockerfile
        ports:
            - "3000:3000"
            - "5555:5555"
        depends_on:
            - postgres
        environment:
            - DATABASE_URL=postgresql://postgres:passward@test_postgres:5432/medmanage?schema=public
volumes:
    postgres-store:
    mongo-store:
