version: "3"

services:
    voicevox:
        container_name: voicevox
        image: "voicevox/voicevox_engine:cpu-ubuntu20.04-latest"
        # ports:
        # - "50021:50021"
    broker-service:
        container_name: broker-service
        build:
            context: ./../broker-service
            dockerfile: ./../broker-service/broker-service.Dockerfile
        ports:
            - "8080:8080"
    speaker-service:
        container_name: speaker-service
        build:
            context: ./../speaker-service
            dockerfile: ./../speaker-service/speaker-service.Dockerfile
        ports:
            - "8081:8080"
    surroundings-store:
        container_name: surroundings-store
        build:
            context: ../surroundings-store
            dockerfile: ../surroundings-store/surroundings-store.Dockerfile
        ports:
            - "9000:9000"
        networks:
            - service_db
            - default
    medicine-api:
        container_name: medicine-api
        build:
            context: ../medicine-api
            dockerfile: ../medicine-api/Dockerfile
        ports:
            - "3000:3000"
            - "5555:5555"
        networks:
            - service_db
            - default
        environment:
            - DATABASE_URL=postgresql://postgres:passward@postgres:5432/medmanage?schema=public
networks:
    service_db:
        external: true
